apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: petstore-go-app
  namespace: openshift-gitops
spec:
  generators:      
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: dev-placement
      requeueAfterSeconds: 180
  
  template:
    metadata:
      name: 
    spec:
      source:
        repoURL: https://github.com/rprakashg-redhat/petstore-go
        path: deploy/k8s/overlays/dev
        targetRevision: main

      destination:
        namespace: demos
        server: {{ server }}
    
    project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false