name: Build publish techdocs
on:
  push:
    branches:
      - main
    paths:
      - "docs"
      - 'mkdocs.yaml'
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ vars.TECHDOCS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      NAMESPACE: ${{ vars.K8S_NAMESPACE }}
      KIND: 'Component'

    steps:
    - uses: actions/checkout@v3
    - name: setup node 
      uses: actions/setup-node@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: download, validate, install plantuml and its dependencies
      run: |
        curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download
        echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c -
        mv plantuml.jar /opt/plantuml.jar
        mkdir -p "$HOME/.local/bin"
        echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> "$HOME/.local/bin/plantuml"
        chmod +x "$HOME/.local/bin/plantuml"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        sudo apt-get install -y graphviz
    - name: Install techdocs-cli
      run: sudo npm install -g @techdocs/cli
    - name: Install mkdocs and mkdocs plugins
      run: python -m pip install mkdocs-techdocs-core==1.*
    - name: Generate docs site
      run: techdocs-cli generate --no-docker --verbose
    - name: get repo name
      run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
    - name: Publish docs site
      run: | 
        techdocs-cli publish --publisher-type awsS3 \
          --storage-name $TECHDOCS_S3_BUCKET_NAME \
          --entity $NAMESPACE/$KIND/$REPO_NAME
